name: icones
description: Icon explorer package for Flutter framework inspired by the work of @antfu.
version: 1.0.3
homepage: https://fa-fifi.is-a.dev/icones
repository: https://github.com/fa-fifi/icones

environment:
  sdk: ">=3.1.2 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  fonts:
    - family: CarbonIcon
      fonts:
        - asset: assets/fonts/CarbonIcon.ttf
    - family: MingCuteIcon
      fonts:
        - asset: assets/fonts/MingCuteIcon.ttf

topics:
  - Carbon
  - MingCuteIcon