name: icones
description: Icon explorer package for Flutter framework inspired by the work of @antfu.
version: 1.0.1
repository: https://github.com/fa-fifi/icones

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

flutter:
  fonts:
    - family: MingCuteIcon
      fonts:
        - asset: assets/fonts/MingCuteIcon.ttf
    - family: Carbon
      fonts:
        - asset: assets/fonts/Carbon.ttf
