name: Github Page

on:
  workflow_run:
    workflows: publish
    types: completed
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
      - uses: bluefireteam/flutter-gh-pages@v8
        with:
          baseHref: /icones/
          workingDir: example
          webRenderer: canvaskit