name: Github Page

on:
  workflow_run:
    workflows: Publish Package
    types: completed
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup flutter environment
        uses: subosito/flutter-action@v2
      - name: Build and deploy flutter web app
        uses: bluefireteam/flutter-gh-pages@v8
        with:
          baseHref: /icones/
          workingDir: example
          webRenderer: canvaskit